embed_assets: off

javascripts:
  workspace:
    - public/javascripts/lib/jquery/jquery.min.js
    - public/javascripts/backbone/underscore.js
    - public/javascripts/backbone/backbone.js
#    - public/javascripts/lib/juquery/jquery.min.js
    - public/javascripts/lib/**/*.js
# app comes here
    - public/javascripts/backbone/application.js
    - public/javascripts/backbone/models/**/*.js     	
    - public/javascripts/backbone/controllers/*.js     	
    - public/javascripts/backbone/views/**/*.js
    - public/javascripts/backbone/helpers/*.js     	
    - app/views/backbone/*.jst

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/widgets/*.css
  workspace:
    - public/stylesheets/buttons.css
  empty:
    - public/stylesheets/pages/empty.css