embed_assets: off
compress_assets: off
package_assets: on
gzip_assets: off
template_function: off

javascripts:    
  common: &common
    - public/javascripts/lib/jquery/jquery-1.8.0.js
    # this includes tooltips
    - public/javascripts/lib/jquery/jquery.tools.min.js
    # tagcloud stuff
    - public/javascripts/lib/tagcanvas-1.17.js
    # nice editor
    - public/javascripts/lib/nicEdit.js
    # these things need to go first...
    - public/javascripts/lib/jquery/plugins/jquery.effects.core.js
    - public/javascripts/lib/jquery/plugins/jquery.ui.core.js
    - public/javascripts/lib/jquery/plugins/jquery.ui.position.js
    - public/javascripts/lib/jquery/plugins/jquery.ui.widget.js
    - public/javascripts/lib/bootstrap-modal.js
# and then rest of jquery.ui can go
    - public/javascripts/lib/jquery/plugins/*.js
# other stuff.. order is not so critical
    - public/javascripts/lib/jquery/jquery.fastconfirm.js
    - public/javascripts/lib/jquery/jquery.tabSlideOut.v1.3.js
    - public/javascripts/lib/jquery/jquery.blockUI.js
    - public/javascripts/juggernaut.js 
#libs
    - public/javascripts/lib/underscore/underscore.js
    - public/javascripts/lib/backbone/backbone.js
    - public/javascripts/lib/backbone.marionette/lib/backbone.marionette.js
    - public/javascripts/lib/backbone.geppetto/backbone.geppetto.js
# not sure if this one is needed
#    - public/javascripts/lib/backbonerailsauthtokenadapter.js
    - public/javascripts/lib/notifier.js
# visualization stuff
#    - public/javascripts/yahoo-dom-event.js
#    - public/javascripts/helpers.js
#    - public/javascripts/public_smo_scripts.js
#    - public/javascripts/jit.js
#    - public/javascripts/jit-yc.js
#    - public/javascripts/balloon.js
#    - public/javascripts/balloon.config.js    
#    - public/javascripts/box.js
#    - public/javascripts/forcedirected.js
#    - public/javascripts/interpolation.js

  backbone: &backbone
# this contains App object declaration
    - public/javascripts/application.js
# we'll see if we're going to need this guys
#    - public/javascripts/backbone/models/**/*.js        
#    - public/javascripts/backbone/controllers/*.js      
#    - public/javascripts/backbone/views/**/*.js
#    - public/javascripts/backbone/helpers/*.js          
    - public/javascripts/backbone/**/*.js

  templates: &templates
#   - app/views/backbone/*.jst
    - public/javascripts/backbone/**/*.jst

  app: &app
    - *templates
    - *backbone 
    - public/javascripts/run_init.js

stylesheets:
  common:
    - public/stylesheets/buttons.css
    - public/stylesheets/decisions.css
    - public/stylesheets/jquery.fastconfirm.css 
    - public/stylesheets/jquery-ui-1.8.12.custom.css
    - public/stylesheets/jquery.cluetip.css
    - public/stylesheets/bootstrap.css
    - public/stylesheets/bootstrap-responsive.css
    - public/stylesheets/saw.css
  workspace:
  empty:
#    - public/stylesheets/pages/empty.css
