embed_assets: off
compress_assets: off
package_assets: on
gzip_assets: off

javascripts:    
  common: &common
    - public/javascripts/lib/jquery/jquery.min.js
    - public/javascripts/lib/jquery/jquery-ui-1.8.custom.min.js
    - public/javascripts/lib/jquery/jquery.fastconfirm.js
# this one was originally downloaded over the juggernaut static node server...
    - public/javascripts/juggernaut.js
    - public/javascripts/backbone/underscore.js
    - public/javascripts/backbone/backbone.js
    - public/javascripts/backbone/backbonerailsauthtokenadapter.js
    - public/javascripts/backbone/notifier.js
    - public/javascripts/lib/**/*.js

  backbone: &backbone
    - public/javascripts/backbone/models/**/*.js        
    - public/javascripts/backbone/controllers/*.js      
    - public/javascripts/backbone/views/**/*.js
    - public/javascripts/backbone/helpers/*.js          
    - app/views/backbone/*.jst
  workspace:
# app comes here
    - *common
    - public/javascripts/backbone/items.js
    - *backbone

  projects:
    - *common
    - public/javascripts/backbone/projects.js
    - *backbone

stylesheets:
  common:
#    - public/stylesheets/reset.css
#    - public/stylesheets/widgets/*.css
    - public/stylesheets/buttons.css
    - public/stylesheets/decisions.css
    - public/stylesheets/jquery.fastconfirm.css 
  workspace:
  empty:
#    - public/stylesheets/pages/empty.css
