embed_assets: off
compress_assets: off
package_assets: on
gzip_assets: off

javascripts:    
  common: &common
    - public/javascripts/lib/jquery/jquery-1.5.1.js
#    - public/javascripts/lib/jquery/jquery-1.5.1.min.js
#    - public/javascripts/lib/jquery/jquery-ui-1.8.12.custom.js
    # this includes tooltips
    - public/javascripts/lib/jquery/jquery.tools.min.js
    # these things need to go first...
    - public/javascripts/lib/jquery/plugins/jquery.effects.core.js
    - public/javascripts/lib/jquery/plugins/jquery.ui.core.js
    - public/javascripts/lib/jquery/plugins/jquery.ui.position.js
    - public/javascripts/lib/jquery/plugins/jquery.ui.widget.js
# and then rest of jquery.ui can go
    - public/javascripts/lib/jquery/plugins/*.js
# other stuff.. order is not so critical
    - public/javascripts/lib/jquery/jquery.fastconfirm.js
    - public/javascripts/lib/jquery/jquery.tabSlideOut.v1.3.js
    - public/javascripts/lib/jquery/jquery.blockUI.js
# this one was originally downloaded over the juggernaut static node server...
    - public/javascripts/juggernaut.js
    - public/javascripts/backbone/underscore.js
    - public/javascripts/backbone/backbone.js
    - public/javascripts/backbone/backbonerailsauthtokenadapter.js
    - public/javascripts/backbone/notifier.js
 #   - public/javascripts/lib/**/*.js
    - public/javascripts/application.js
# visualization stuff
    - public/javascripts/yahoo-dom-event.js
    - public/javascripts/helpers.js
    - public/javascripts/public_smo_scripts.js
    - public/javascripts/jit.js
    - public/javascripts/jit-yc.js
    - public/javascripts/balloon.js
    - public/javascripts/balloon.config.js    
    - public/javascripts/box.js
    - public/javascripts/forcedirected.js
    - public/javascripts/interpolation.js

  backbone: &backbone
    - public/javascripts/backbone/models/**/*.js        
    - public/javascripts/backbone/controllers/*.js      
    - public/javascripts/backbone/views/**/*.js
    - public/javascripts/backbone/helpers/*.js          
    - app/views/backbone/*.jst
  workspace:
# app comes here
    - public/javascripts/backbone/items.js
    - *backbone

  projects:
    - public/javascripts/backbone/projects.js
    - *backbone

stylesheets:
  common:
#    - public/stylesheets/reset.css
#    - public/stylesheets/widgets/*.css
    - public/stylesheets/buttons.css
    - public/stylesheets/decisions.css
    - public/stylesheets/jquery.fastconfirm.css 
    - public/stylesheets/jquery-ui-1.8.12.custom.css
    - public/stylesheets/jquery.cluetip.css
# visualization stuff
    - public/stylesheets/infovis.css
  workspace:
  empty:
#    - public/stylesheets/pages/empty.css
