defaults: &defaults
    database: saw
    host: localhost
    
development:
  <<: *defaults
#  database: saw_development

test:
  <<: *defaults

# set these environment variables on your prod server
production:
    uri: <%= ENV['MONGOHQ_URL'] %>
