defaults: &defaults
    uri: <%= ENV['MONGOHQ_URL'] %>
    
development:
  <<: *defaults
#  database: saw_development

test:
  <<: *defaults
#  database: saw_test

# set these environment variables on your prod server
production:
    <<: *defaults    
