defaults: &defaults
    host: <%= ENV['MONGOID_HOST'] %>
    port: <%= ENV['MONGOID_PORT'] %>
    username: <%= ENV['MONGOID_USERNAME'] %>
    password: <%= ENV['MONGOID_PASSWORD'] %>
    database: <%= ENV['MONGOID_DATABASE'] %>

development:
  <<: *defaults
#  database: saw_development

test:
  <<: *defaults
#  database: saw_test

# set these environment variables on your prod server
production:
    <<: *defaults    
